# Generated by Django 4.2.4 on 2024-03-29 01:06

from django.db import migrations, models
import marketplace.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', models.ImageField(upload_to=marketplace.models.product_directory_path)),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
