# Generated by Django 4.2.4 on 2024-03-29 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketPlace',
            new_name='Product',
        ),
    ]
