# Generated by Django 4.2.4 on 2024-03-30 13:47

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=marketplace.models.product_directory_path),
        ),
    ]
