# Generated by Django 4.2.4 on 2024-03-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_product_image'),
        ('marketplace', '0005_category_product_category'),
    ]

    operations = [
    ]
