# Generated by Django 4.2.4 on 2024-03-31 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
