# Generated by Django 4.2.4 on 2024-04-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_merge_20240331_2330'),
        ('marketplace', '0006_rename_category_product_category'),
    ]

    operations = [
    ]
